### ISSUE TITLE
birdnet appliance

### ISSUE THREAD

**Issue by sorokivski** [SR-71-group/birdanalysis#5]
## Running BirdNET on Migration Call Data

Defining Baseline Performance

- [ ] Run BirdNET on our bird migration call data to establish a baseline performance for comparison with future models.

### Expected Results: 

- [ ] Identifying Misclassifications: common errors and misclassifications that occur due to BirdNET’s focus on daytime calls and general bird sounds. 
- [ ] Performance metrics (accuracy, false positives, etc.)
- [ ] Report on misclassified bird species and time-of-day mismatches
- [ ] Insights for future model improvements

**Comment by mirahse** [comment]
![birnet_conf_mat](https://github.com/user-attachments/assets/9a214c5b-de3d-4f04-8985-22b9535db94e)
- birdnet classification with highest confidence is chosen for each file
- if birdnet detected species that is not in the true labels, birdnet detection = otherspecies
- if birdnet did not classify any bird = nopred
